#!/usr/bin/env python3
# Copyright 2026 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Run an isolated SDPA sweep for vanilla, flash-HBM, and on-chip variants.

The parent process spawns one child process per shape/variant so Torch-Spyre
configuration flags are read from a clean environment and the device runtime is
not reused across variants.  Each child compiles one SDPA shape, checks value
correctness against PyTorch CPU, measures repeated compiled Spyre calls, and
summarizes generated mixed SDSCs / senprog tokens from ``TORCHINDUCTOR_CACHE_DIR``.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import statistics
import subprocess
import sys
import time
import warnings
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

TAIL_CHARS = 8000


BASE_VARIANT_ENV = {
    "SPYRE_FLASH_ATTENTION_PREFILL": "0",
    "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "0",
    "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_OVERLAP": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_ARTIFACT": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_EXECUTE_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_VALUE_FLOW_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PAIR_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PREFIX_FORCE": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_OVERLAP": "0",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_LOOKAHEAD_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_HOIST_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_SUBPIECE_REUSE": "1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_GROUP_SIZE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_SELF_RESIDENT_SOURCE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_SOURCE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_STAGED": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_CONSUMER_CORE_STATE_INIT": "1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_CONSUMER_DS_TYPE": "",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_CONSUMER_LX_ALLOC_STYLE": "",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_USE_UNICAST": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_FORCE_MC_MODE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_STAGED_HOIST_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LX_BASE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIAL": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_PREFILL_CURRENT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_REDUNDANT_FUTURE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_CURRENT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_EXTERNAL_FUTURE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_OVERLAP_AFTER_SYNC": "1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SOURCE_FANOUT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_LX_BASE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_USE_UNICAST": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_USE_LXSFP_LX_TRANSFERS": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "-2",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_RESTRICT_TO_COPYBACK_CORE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_COPYBACK_WITHOUT_FANOUT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_LOADER_CORE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LX_ROUNDTRIP": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_CORELET1": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "-1",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_DIRECT_SOURCE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_SOURCE_FANOUT": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_LOAD_ONLY": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_BARRIER_ONLY": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_DATA_ONLY": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_REPLACE_CONSUMER": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_COMPUTE_ONLY": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_EXACT_CLONE": "0",
    "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_PRESERVE_CONSUMER_NAME": "0",
    "SPYRE_FLASH_ATTENTION_POINTWISE_HANDOFF": "0",
    "SPYRE_FLASH_ATTENTION_SCORE_SCALE_HANDOFF": "0",
    "SPYRE_ONCHIP_HANDOFF_REALIZE": "0",
    "SPYRE_ONCHIP_ATTENTION_SCORE_HANDOFF": "0",
}


VARIANT_ENV = {
    "vanilla": {
        **BASE_VARIANT_ENV,
    },
    "flash_hbm": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
    },
    "pointwise_only": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_POINTWISE_HANDOFF": "1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_POINTWISE_HANDOFF": "1",
        "SPYRE_FLASH_ATTENTION_SCORE_SCALE_HANDOFF": "1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_master": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_master_layout_xform": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_staged_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_STAGED": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_staged_hoist_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_STAGED_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_hoist_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_serial_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIAL": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_serialize_current_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_redundant_future_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_REDUNDANT_FUTURE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_no_after_sync_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_OVERLAP_AFTER_SYNC": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_corelet1_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_CORELET1": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_tail_current_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_source_fanout_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SOURCE_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_source_fanout_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SOURCE_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_overlap_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_overlap_core31_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_overlap_core31_serialize_loader_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_LOADER_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_warpspec_kv_hbm_prefetch_loader_core31": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_LOADER_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_warpspec_kv_hbm_prefetch_loader_core31_decoupled": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "0",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_SERIALIZE_LOADER_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_overlap_safesrc_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_LX_BASE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_overlap_no_after_sync_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_OVERLAP_AFTER_SYNC": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_unicast_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_USE_UNICAST": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_copyback_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_lxfifo_copyback_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_USE_LXSFP_LX_TRANSFERS": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_local_copyback_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_RESTRICT_TO_COPYBACK_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_direct_copyback_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_COPYBACK_WITHOUT_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_direct_copyback_overlap_core31_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_COPYBACK_WITHOUT_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_direct_copyback_overlap_safesrc_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_LX_BASE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_COPYBACK_WITHOUT_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_direct_copyback_overlap_no_after_sync_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_COPYBACK_WITHOUT_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_OVERLAP_AFTER_SYNC": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_loader_fanout_fulltile_local_copyback_tail_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_FANOUT_RESTRICT_TO_COPYBACK_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LOADER_FANOUT_FULL_TILE_PIECES": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_TAIL_CURRENT": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_kv_hbm_prefetch_roundtrip_corelet1_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_LX_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_HBM_PREFETCH_CORELET1": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_lookahead": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_LOOKAHEAD_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "onchip_hbm_kv_layout_xform_hoist": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA": "1",
        "SPYRE_FLASH_ATTENTION_ONCHIP_SDPA_LAYOUT_XFORM": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": None,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-1",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
    "warp_overlap_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_EXECUTE_TILE": "0",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_OVERLAP": "1",
    },
    "warp_ifn_prefix_probe": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_EXECUTE_TILE": "0",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_OVERLAP": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PREFIX_FORCE": "1",
    },
    "value_flow_tile0": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_VALUE_FLOW_TILE": "0",
    },
    "value_flow_tile1": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_VALUE_FLOW_TILE": "1",
    },
    "value_flow_tile2": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_VALUE_FLOW_TILE": "2",
    },
    "ifn_pair_tile0": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PAIR_TILE": "0",
    },
    "ifn_pair_tile1": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PAIR_TILE": "1",
    },
    "ifn_pair_tile2": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_IFN_PAIR_TILE": "2",
    },
    "layout_xform_pair_tile2": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "2",
    },
    "layout_xform_pair_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
    },
    "layout_xform_pair_overlap_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_OVERLAP": "1",
    },
    "layout_xform_lookahead_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_LOOKAHEAD_TILE": "-2",
    },
    "layout_xform_hoist_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_HOIST_TILE": "-2",
    },
    "layout_xform_hoist_kv_repack_plan_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_HOIST_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PLAN_ARTIFACT": "1",
    },
    "kv_repack_pair_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
    },
    "kv_repack_pair_no_ifn_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
    },
    "kv_repack_pair_no_reuse_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_SUBPIECE_REUSE": "0",
    },
    "kv_repack_pair_group16_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_GROUP_SIZE": "16",
    },
    "kv_repack_pair_group8_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_GROUP_SIZE": "8",
    },
    "kv_repack_pair_group4_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_GROUP_SIZE": "4",
    },
    "kv_repack_pair_self_resident_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_SELF_RESIDENT_SOURCE": "1",
    },
    "kv_repack_pair_hbm_source_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_SOURCE": "1",
    },
    "kv_repack_pair_hbm_direct_load_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_pair_hbm_staged_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_STAGED": "1",
    },
    "kv_repack_pair_hbm_direct_load_no_ifn_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_pair_hbm_direct_load_no_csi_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_CORE_STATE_INIT"
        ): "0",
    },
    "kv_repack_pair_hbm_direct_load_no_ifn_no_csi_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_CORE_STATE_INIT"
        ): "0",
    },
    "kv_repack_pair_hbm_direct_load_dsinput_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_CORE_STATE_INIT"
        ): "0",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_DS_TYPE"
        ): "INPUT",
    },
    "kv_repack_pair_hbm_direct_load_canonical_name_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_LX_ALLOC_STYLE"
        ): "canonical_name",
    },
    "kv_repack_pair_hbm_direct_load_canonical_loop_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_IFN_TRANSFER": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_HBM_DIRECT_LOAD": "1",
        (
            "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_"
            "CONSUMER_LX_ALLOC_STYLE"
        ): "canonical_loop",
    },
    "kv_repack_pair_force_mc1_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_FORCE_MC_MODE": "1",
    },
    "kv_repack_pair_force_mc2_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_FORCE_MC_MODE": "2",
    },
    "kv_repack_pair_force_mc3_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_FORCE_MC_MODE": "3",
    },
    "kv_repack_copyback_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
    },
    "kv_repack_copyback_group4_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_PAIR_GROUP_SIZE": "4",
    },
    "kv_repack_copyback_direct_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_DIRECT_SOURCE": "1",
    },
    "kv_repack_copyback_hbm_roundtrip_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
    },
    "kv_repack_copyback_hbm_source_fanout_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_SOURCE_FANOUT": "1",
    },
    "kv_repack_copyback_hbm_direct_load_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_direct_load_core0_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "0",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_direct_load_core1_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_direct_load_core8_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "8",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_direct_load_core16_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "16",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_direct_load_core31_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_CORE": "31",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_DIRECT_LOAD": "1",
    },
    "kv_repack_copyback_hbm_load_only_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_LOAD_ONLY": "1",
    },
    "kv_repack_copyback_hbm_barrier_only_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_BARRIER_ONLY": "1",
    },
    "kv_repack_copyback_hbm_load_data_only_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_LOAD_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_DATA_ONLY": "1",
    },
    "kv_repack_copyback_hbm_barrier_data_only_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_BARRIER_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_DATA_ONLY": "1",
    },
    "kv_repack_copyback_hbm_barrier_replace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_BARRIER_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_REPLACE_CONSUMER": "1",
    },
    "kv_repack_copyback_hbm_load_replace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_LOAD_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_REPLACE_CONSUMER": "1",
    },
    "kv_repack_copyback_hbm_compute_replace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_REPLACE_CONSUMER": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_COMPUTE_ONLY": "1",
    },
    "kv_repack_copyback_hbm_exact_clone_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_EXACT_CLONE": "1",
    },
    "kv_repack_copyback_hbm_exact_clone_inplace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_EXACT_CLONE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_PRESERVE_CONSUMER_NAME": "1",
    },
    "kv_repack_copyback_hbm_compute_inplace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_COMPUTE_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_PRESERVE_CONSUMER_NAME": "1",
    },
    "kv_repack_copyback_hbm_barrier_inplace_auto": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_TILE": "-2",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_HBM_ROUNDTRIP_BARRIER_ONLY": "1",
        "SPYRE_FLASH_ATTENTION_KV_REPACK_BROADCAST_COPYBACK_PRESERVE_CONSUMER_NAME": "1",
    },
    "onchip_layout_xform": {
        **BASE_VARIANT_ENV,
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE": "1",
        "SPYRE_FLASH_ATTENTION_POINTWISE_HANDOFF": "1",
        "SPYRE_FLASH_ATTENTION_SCORE_SCALE_HANDOFF": "1",
        "SPYRE_FLASH_ATTENTION_MIXED_PIPELINE_LAYOUT_XFORM_PAIR_TILE": "-2",
        "SPYRE_ONCHIP_HANDOFF_MIN_BYTES": "0",
    },
}


def _parse_csv(values: str) -> list[str]:
    return [value.strip() for value in values.split(",") if value.strip()]


def _percentile(sorted_values: list[float], pct: float) -> float:
    if not sorted_values:
        return float("nan")
    if len(sorted_values) == 1:
        return sorted_values[0]
    rank = (len(sorted_values) - 1) * pct
    low = int(rank)
    high = min(low + 1, len(sorted_values) - 1)
    frac = rank - low
    return sorted_values[low] * (1 - frac) + sorted_values[high] * frac


def _short_rejections(reasons: list[str], limit: int = 12) -> dict:
    return {
        "count": len(reasons),
        "first": reasons[:limit],
        "truncated": len(reasons) > limit,
    }


def _original_sdsc_bundles(cache_dir: Path) -> dict[str, list[dict]]:
    bundles: dict[str, list[tuple[int, dict]]] = {}
    for path in sorted(cache_dir.rglob("sdsc_*.json")):
        if "/debug/" in str(path) or "mixed" in path.name:
            continue
        match = re.match(r"sdsc_(\d+)_", path.name)
        if match is None:
            continue
        try:
            data = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict) or not data:
            continue
        bundles.setdefault(str(path.parent.relative_to(cache_dir)), []).append(
            (int(match.group(1)), data)
        )

    return {
        dirname: [data for _idx, data in sorted(items)]
        for dirname, items in sorted(bundles.items())
    }


def _layout_xform_candidate_summary(cache_dir: Path) -> list[dict]:
    try:
        from torch_spyre._inductor import onchip_realize as rz
    except (ImportError, AttributeError):
        return []

    candidates = []
    for dirname, sdscs in _original_sdsc_bundles(cache_dir).items():
        if len(sdscs) < 2:
            continue
        try:
            lookahead_rejections = (
                rz.flash_attention_layout_xform_lookahead_rejection_reasons(
                    sdscs,
                    rz.LAYOUT_XFORM_PAIR_AUTO_TILE,
                )
            )
            hoist_rejections = rz.flash_attention_layout_xform_hoist_rejection_reasons(
                sdscs,
                rz.LAYOUT_XFORM_PAIR_AUTO_TILE,
            )
            pair_rejections = rz.flash_attention_layout_xform_pair_rejection_reasons(
                sdscs,
                rz.LAYOUT_XFORM_PAIR_AUTO_TILE,
            )
        except (KeyError, TypeError, ValueError):
            continue
        candidates.append(
            {
                "dir": dirname,
                "sdscs": len(sdscs),
                "lookahead_selectable": not lookahead_rejections,
                "lookahead_rejections": _short_rejections(lookahead_rejections),
                "hoist_selectable": not hoist_rejections,
                "hoist_rejections": _short_rejections(hoist_rejections),
                "pair_selectable": not pair_rejections,
                "pair_rejections": _short_rejections(pair_rejections),
            }
        )
    return candidates


def _summarize_cache(cache_dir: Path) -> dict:
    mixed = []
    for path in sorted(cache_dir.rglob("sdsc_*.json")):
        if "/debug/" in str(path):
            continue
        try:
            data = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict) or not data:
            continue
        name, body = next(iter(data.items()))
        if not isinstance(body, dict):
            continue
        opfuncs = body.get("opFuncsUsed_", []) or []
        datadscs = body.get("datadscs_", []) or []
        if not opfuncs and not datadscs:
            continue
        flash_pipeline = body.get("flashAttentionPipeline_")
        first_dataop = None
        if datadscs:
            dataop_name, dataop_body = next(iter(datadscs[0].items()))
            first_labeled = (dataop_body.get("labeledDs_") or [{}])[0]
            first_piece = (first_labeled.get("PieceInfo") or [{}])[0]
            placement = (first_piece.get("PlacementInfo") or [{}])[0]
            first_dataop = {
                "name": dataop_name,
                "layout": first_labeled.get("layoutDimOrder_"),
                "stick": first_labeled.get("stickDimOrder_"),
                "startAddr": placement.get("startAddr"),
                "memId": placement.get("memId"),
            }
        mixed.append(
            {
                "file": str(path.relative_to(cache_dir)),
                "name": name,
                "opFuncsUsed": opfuncs,
                "datadscs": len(datadscs),
                "first_dataop": first_dataop,
                "flash_pipeline": flash_pipeline,
            }
        )

    senprog = []
    for path in sorted(cache_dir.rglob("senprog.txt")):
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        rel = str(path.parent.relative_to(cache_dir))
        if "debug/" not in rel:
            continue
        counts = {
            token: text.count(token)
            for token in ("HBM", "L3_LDU", "L3_STU", "LX_LDSTU", "PT", "SFP")
        }
        if any(counts.values()):
            senprog.append({"dir": rel, **counts})

    return {
        "mixed_sdscs": mixed,
        "senprog": senprog,
        "layout_xform_candidates": _layout_xform_candidate_summary(cache_dir),
    }


def _run_child(args: argparse.Namespace) -> int:
    import torch
    import torch.nn.functional as F
    import torch_spyre

    torch_spyre._autoload()

    from torch_spyre._inductor import config as spyre_config
    from torch_spyre.ops.fallbacks import FallbackWarning

    if args.forbid_fallbacks:
        warnings.simplefilter("error", FallbackWarning)

    torch.manual_seed(args.seed)
    try:
        torch._dynamo.reset_code_caches()
        torch._inductor.codecache.FxGraphCache.clear()
    except AttributeError:
        pass

    shape = (args.batch, args.heads, args.length, args.dim)
    q_cpu = torch.randn(shape, dtype=torch.float16)
    k_cpu = torch.randn(shape, dtype=torch.float16)
    v_cpu = torch.randn(shape, dtype=torch.float16)

    def sdpa(q, k, v):
        return F.scaled_dot_product_attention(q, k, v, is_causal=args.is_causal)

    reference = sdpa(q_cpu, k_cpu, v_cpu)
    q_dev = q_cpu.to("spyre")
    k_dev = k_cpu.to("spyre")
    v_dev = v_cpu.to("spyre")

    compiled = torch.compile(sdpa, backend="inductor")

    compile_start = time.perf_counter()
    result = compiled(q_dev, k_dev, v_dev)
    torch.spyre.synchronize()
    compile_run_ms = (time.perf_counter() - compile_start) * 1000.0

    result_cpu = result.cpu()
    torch.testing.assert_close(
        result_cpu,
        reference,
        equal_nan=True,
        atol=args.atol,
        rtol=args.rtol,
    )
    max_abs_error = float((result_cpu - reference).abs().max().item())

    for _ in range(args.warmup):
        compiled(q_dev, k_dev, v_dev)
        torch.spyre.synchronize()

    samples_ms = []
    for _ in range(args.iters):
        start = time.perf_counter()
        compiled(q_dev, k_dev, v_dev)
        torch.spyre.synchronize()
        samples_ms.append((time.perf_counter() - start) * 1000.0)

    ordered = sorted(samples_ms)
    cache_dir = Path(os.environ["TORCHINDUCTOR_CACHE_DIR"])
    payload = {
        "status": "ok",
        "variant": args.variant,
        "shape": {
            "batch": args.batch,
            "heads": args.heads,
            "length": args.length,
            "dim": args.dim,
        },
        "block_size": spyre_config.flash_attention_prefill_block_size,
        "is_causal": args.is_causal,
        "fallbacks_forbidden": args.forbid_fallbacks,
        "block_size_env": os.environ.get(
            "SPYRE_FLASH_ATTENTION_PREFILL_BLOCK_SIZE", ""
        ),
        "cache_dir": str(cache_dir),
        "compile_run_ms": compile_run_ms,
        "warmup": args.warmup,
        "iters": args.iters,
        "median_ms": statistics.median(samples_ms),
        "mean_ms": statistics.mean(samples_ms),
        "min_ms": min(samples_ms),
        "max_ms": max(samples_ms),
        "p90_ms": _percentile(ordered, 0.90),
        "max_abs_error": max_abs_error,
        **_summarize_cache(cache_dir),
    }
    print("RESULT_JSON:" + json.dumps(payload, sort_keys=True))
    return 0


def _child_env(args: argparse.Namespace, variant: str, length: int) -> dict[str, str]:
    env = os.environ.copy()
    for key, value in VARIANT_ENV[variant].items():
        if value is None:
            env.pop(key, None)
        else:
            env[key] = value
    if args.block_size > 0:
        env["SPYRE_FLASH_ATTENTION_PREFILL_BLOCK_SIZE"] = str(args.block_size)
    else:
        env.pop("SPYRE_FLASH_ATTENTION_PREFILL_BLOCK_SIZE", None)
    for item in args.env:
        if "=" not in item:
            raise ValueError(f"--env override must be KEY=VALUE, got {item!r}")
        key, value = item.split("=", 1)
        if not key:
            raise ValueError(f"--env override has empty key: {item!r}")
        env[key] = value
    env["DXP_DEBUG"] = "1" if args.dxp_debug else "0"
    nonce = random.randint(0, 999999)
    cache_prefix = args.cache_prefix.rstrip("/")
    env["TORCHINDUCTOR_CACHE_DIR"] = (
        f"{cache_prefix}-{variant}-B{args.batch}-H{args.heads}"
        f"-L{length}-D{args.dim}-C{int(args.is_causal)}-{os.getpid()}-{nonce}"
    )
    return env


def _tail_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        value = value.decode("utf-8", errors="replace")
    return str(value)[-TAIL_CHARS:]


def _run_parent(args: argparse.Namespace) -> int:
    results = []
    script = Path(__file__).resolve()
    lengths = [int(value) for value in _parse_csv(args.lengths)]
    variants = _parse_csv(args.variants)
    for variant in variants:
        if variant not in VARIANT_ENV:
            raise ValueError(f"unknown variant {variant!r}; valid={sorted(VARIANT_ENV)}")

    for length in lengths:
        for variant in variants:
            cmd = [
                sys.executable,
                str(script),
                "--child",
                "--variant",
                variant,
                "--batch",
                str(args.batch),
                "--heads",
                str(args.heads),
                "--length",
                str(length),
                "--dim",
                str(args.dim),
                "--warmup",
                str(args.warmup),
                "--iters",
                str(args.iters),
                "--seed",
                str(args.seed + length),
                "--atol",
                str(args.atol),
                "--rtol",
                str(args.rtol),
            ]
            if args.is_causal:
                cmd.append("--is-causal")
            if args.forbid_fallbacks:
                cmd.append("--forbid-fallbacks")
            env = _child_env(args, variant, length)
            started = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    env=env,
                    text=True,
                    capture_output=True,
                    timeout=args.timeout_s,
                )
            except subprocess.TimeoutExpired as exc:
                elapsed_s = time.perf_counter() - started
                row = {
                    "status": "timeout",
                    "variant": variant,
                    "is_causal": args.is_causal,
                    "fallbacks_forbidden": args.forbid_fallbacks,
                    "shape": {
                        "batch": args.batch,
                        "heads": args.heads,
                        "length": length,
                        "dim": args.dim,
                    },
                    "cache_dir": env["TORCHINDUCTOR_CACHE_DIR"],
                    "timeout_s": args.timeout_s,
                    "elapsed_s": elapsed_s,
                    "stdout_tail": _tail_text(exc.stdout),
                    "stderr_tail": _tail_text(exc.stderr),
                }
                row.update(_summarize_cache(Path(env["TORCHINDUCTOR_CACHE_DIR"])))
                results.append(row)
                _print_last_result(results[-1])
                continue
            elapsed_s = time.perf_counter() - started
            result_line = None
            for line in proc.stdout.splitlines():
                if line.startswith("RESULT_JSON:"):
                    result_line = line[len("RESULT_JSON:"):]
            if result_line is None or proc.returncode != 0:
                row = {
                    "status": "failed",
                    "variant": variant,
                    "is_causal": args.is_causal,
                    "fallbacks_forbidden": args.forbid_fallbacks,
                    "shape": {
                        "batch": args.batch,
                        "heads": args.heads,
                        "length": length,
                        "dim": args.dim,
                    },
                    "cache_dir": env["TORCHINDUCTOR_CACHE_DIR"],
                    "returncode": proc.returncode,
                    "elapsed_s": elapsed_s,
                    "stdout_tail": _tail_text(proc.stdout),
                    "stderr_tail": _tail_text(proc.stderr),
                }
                row.update(_summarize_cache(Path(env["TORCHINDUCTOR_CACHE_DIR"])))
                results.append(row)
            else:
                payload = json.loads(result_line)
                payload["elapsed_s"] = elapsed_s
                results.append(payload)
            _print_last_result(results[-1])

    if args.output_json:
        Path(args.output_json).write_text(json.dumps(results, indent=2, sort_keys=True))
    return 1 if any(row.get("status") != "ok" for row in results) else 0


def _print_last_result(row: dict) -> None:
    shape = row.get("shape", {})
    prefix = (
        f"L={shape.get('length')} {row.get('variant')} "
        f"status={row.get('status')}"
    )
    if row.get("status") == "ok":
        mixed = len(row.get("mixed_sdscs", []))
        print(
            f"{prefix} median={row['median_ms']:.6f}ms "
            f"mean={row['mean_ms']:.6f}ms max_err={row['max_abs_error']:.6g} "
            f"mixed={mixed} cache={row['cache_dir']}",
            flush=True,
        )
    else:
        print(
            f"{prefix} rc={row.get('returncode')} cache={row.get('cache_dir')}",
            flush=True,
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--child", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--variant", default="onchip")
    parser.add_argument("--variants", default="vanilla,flash_hbm,onchip")
    parser.add_argument("--batch", type=int, default=1)
    parser.add_argument("--heads", type=int, default=2)
    parser.add_argument("--length", type=int, default=128)
    parser.add_argument("--lengths", default="128,256")
    parser.add_argument("--dim", type=int, default=64)
    parser.add_argument(
        "--block-size",
        type=int,
        default=64,
        help="flash prefill block size; 0 leaves the environment unset",
    )
    parser.add_argument("--warmup", type=int, default=3)
    parser.add_argument("--iters", type=int, default=10)
    parser.add_argument("--seed", type=int, default=0xA771)
    parser.add_argument("--atol", type=float, default=0.1)
    parser.add_argument("--rtol", type=float, default=0.1)
    parser.add_argument("--is-causal", action="store_true")
    parser.add_argument(
        "--forbid-fallbacks",
        action="store_true",
        help=(
            "treat Torch-Spyre CPU fallback warnings as errors in child runs; "
            "useful as a readiness gate for removing fallback-only paths"
        ),
    )
    parser.add_argument("--timeout-s", type=float, default=180.0)
    parser.add_argument("--cache-prefix", default="/tmp/sdpa-onchip-sweep")
    parser.add_argument("--output-json", default="")
    parser.add_argument(
        "--env",
        action="append",
        default=[],
        help="extra KEY=VALUE child environment override applied after variant defaults",
    )
    parser.add_argument(
        "--dxp-debug",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    args = parser.parse_args(argv)

    if args.child:
        return _run_child(args)
    return _run_parent(args)


if __name__ == "__main__":
    raise SystemExit(main())
