#!/usr/bin/env python3
# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Compile-only same-artifact splice for an LX restickify bridge frame.

This is a packaging probe.  It copies a normal Torch-Spyre fused code directory
and replaces the middle ``ReStickifyOpHBM`` program frame inside the existing
``loadprogram_to_device/*/init.txt`` with a Stage 152 LX bridge frame.  It does
not launch hardware.

Unlike ``restickify_lx_neighbor_frame_splice.py``, this tool does not require a
DXP debug rerun.  It can infer frame boundaries from the fused runtime init
stream by looking for program-frame header flits, or accept explicit frame sizes
when a caller wants full control.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import struct
from pathlib import Path
from typing import Any


def _read_hex_init(path: Path) -> bytes:
    out = bytearray()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if len(line) != 256:
            raise ValueError(f"{path} has non-256-char init line")
        out.extend(bytes.fromhex(line)[::-1])
    return bytes(out)


def _write_hex_init(path: Path, data: bytes) -> None:
    if len(data) % 128 != 0:
        raise ValueError(f"program init size must be 128-byte aligned: {len(data)}")
    lines = []
    for offset in range(0, len(data), 128):
        lines.append(data[offset : offset + 128][::-1].hex())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _clear_sentinel(frame: bytes) -> bytes:
    if len(frame) < 4:
        raise ValueError("program frame is too small to contain a header word")
    word = struct.unpack_from("<I", frame, 0)[0]
    out = bytearray(frame)
    struct.pack_into("<I", out, 0, word & 0xFFBFFFFF)
    return bytes(out)


def _sdsc_index(path: Path) -> int:
    if not path.name.startswith("sdsc_"):
        return 10**9
    try:
        return int(path.name.split("_", 2)[1])
    except Exception:
        return 10**9


def _sdsc_files(code_dir: Path) -> list[Path]:
    files = sorted(code_dir.glob("sdsc_*.json"), key=_sdsc_index)
    if not files:
        raise ValueError(f"{code_dir} has no sdsc_*.json files")
    return files


def _restickify_position(code_dir: Path) -> int:
    for index, path in enumerate(_sdsc_files(code_dir)):
        if "ReStickify" in path.name:
            return index
        if "ReStickify" in path.read_text(encoding="utf-8", errors="replace"):
            return index
    raise ValueError(f"{code_dir} has no ReStickify SDSC")


def _runtime_init_path(code_dir: Path) -> Path:
    candidates = sorted((code_dir / "loadprogram_to_device").glob("*/init.txt"))
    if len(candidates) != 1:
        raise ValueError(
            f"expected one loadprogram_to_device/*/init.txt, found {len(candidates)}"
        )
    return candidates[0]


def _parse_frame_sizes(text: str) -> list[int]:
    sizes = [int(item.strip()) for item in text.split(",") if item.strip()]
    if not sizes:
        raise ValueError("--frame-sizes did not contain any sizes")
    for size in sizes:
        if size <= 0 or size % 128 != 0:
            raise ValueError(f"frame size must be positive and 128-byte aligned: {size}")
    return sizes


def _looks_like_frame_header(frame: bytes, offset: int) -> bool:
    if offset + 16 > len(frame):
        return False
    chunk = frame[offset : offset + 16]
    word = struct.unpack_from("<I", frame, offset)[0]
    # Program frames generated by these paths have a compact header whose first
    # byte is 0xdd and whose following header bytes are zero-filled.  This is a
    # probe heuristic, so callers can override it with --frame-sizes.
    return chunk[0] == 0xDD and chunk[4:16] == b"\x00" * 12 and word != 0


def _infer_frame_sizes_from_headers(init_bytes: bytes, expected_count: int) -> list[int]:
    starts = [
        offset
        for offset in range(0, len(init_bytes), 128)
        if _looks_like_frame_header(init_bytes, offset)
    ]
    if len(starts) != expected_count:
        raise ValueError(
            "could not infer frame sizes from headers: "
            f"expected {expected_count} headers, found {len(starts)} at {starts}; "
            "pass --frame-sizes"
        )
    starts.append(len(init_bytes))
    return [starts[index + 1] - starts[index] for index in range(expected_count)]


def _bridge_frame(bridge_dir: Path) -> tuple[bytes, str]:
    preferred = bridge_dir / "init_binary_sentinel_cleared.bin"
    if preferred.exists():
        return preferred.read_bytes(), str(preferred)
    raw = bridge_dir / "init_binary.bin"
    if not raw.exists():
        raise FileNotFoundError(
            f"{bridge_dir} has neither init_binary_sentinel_cleared.bin nor init_binary.bin"
        )
    return _clear_sentinel(raw.read_bytes()), str(raw)


def _replacement_frame(path: Path, *, clear_sentinel: bool) -> tuple[bytes, str]:
    if path.is_dir():
        path = _runtime_init_path(path)
    data = _read_hex_init(path)
    if clear_sentinel:
        data = _clear_sentinel(data)
    return data, str(path)


def _parse_replacement_frame(item: str) -> tuple[int, Path]:
    if ":" not in item:
        raise ValueError(
            "--replacement-frame must be formatted as "
            "'<frame-index>:<init-or-code-dir>'"
        )
    index_text, path_text = item.split(":", 1)
    index = int(index_text)
    if index < 0:
        raise ValueError(f"replacement frame index must be non-negative: {index}")
    return index, Path(path_text)


def _load_bridge_summary(bridge_dir: Path) -> dict[str, Any]:
    path = bridge_dir / "summary.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _update_segment_size(code_dir: Path, flits: int) -> dict[str, Any]:
    path = code_dir / "segment_size.json"
    if not path.exists():
        return {"path": "", "updated": False}
    payload = json.loads(path.read_text(encoding="utf-8"))
    segments = payload.get("memReqPerSegment", {})
    const_seg = segments.get("7")
    before = None
    if isinstance(const_seg, dict):
        before = const_seg.get("size")
        const_seg["size"] = flits
    _write_json(path, payload)
    return {"path": str(path), "updated": True, "before": before, "after": flits}


def _update_loadprogram_dsg(code_dir: Path, bytes_size: int) -> dict[str, Any]:
    path = code_dir / "loadprogram_to_device_dsg.txt"
    if not path.exists():
        return {"path": "", "updated": False}
    text = path.read_text(encoding="utf-8")
    before_match = re.search(r"(^A\s+size\s+\d+\s+)(\d+)(\s*$)", text, re.MULTILINE)
    before = int(before_match.group(2)) if before_match else None
    patched = re.sub(
        r"(^A\s+size\s+\d+\s+)\d+(\s*$)",
        rf"\g<1>{bytes_size}\2",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    path.write_text(patched, encoding="utf-8")
    return {"path": str(path), "updated": patched != text, "before": before, "after": bytes_size}


def _update_spyrecode(code_dir: Path, data: bytes) -> dict[str, Any]:
    spyre_dir = code_dir / "spyreCodeDir"
    if not spyre_dir.exists():
        return {"path": "", "updated": False}
    (spyre_dir / "init_binary.bin").write_bytes(data)
    spyrecode = spyre_dir / "spyrecode.json"
    if not spyrecode.exists():
        return {"path": str(spyre_dir), "updated": True, "spyrecode": False}
    payload = json.loads(spyrecode.read_text(encoding="utf-8"))
    updates = 0
    for section in ("JobPreparationPlan", "JobExecPlan"):
        for command in payload.get(section, []) or []:
            props = command.get("properties") or {}
            if "size" in props:
                props["size"] = str(len(data))
                updates += 1
    _write_json(spyrecode, payload)
    return {"path": str(spyre_dir), "updated": True, "spyrecode_updates": updates}


def _header_word(data: bytes, offset: int = 0) -> int | None:
    if offset + 4 > len(data):
        return None
    return struct.unpack_from("<I", data, offset)[0]


def splice(args: argparse.Namespace) -> dict[str, Any]:
    source_dir = Path(args.code_dir).resolve()
    code_dir = source_dir
    if args.output_dir:
        output_dir = Path(args.output_dir).resolve()
        if output_dir.exists() and args.clean:
            shutil.rmtree(output_dir)
        if output_dir.exists():
            raise FileExistsError(output_dir)
        shutil.copytree(source_dir, output_dir)
        code_dir = output_dir

    init_path = _runtime_init_path(code_dir)
    original = _read_hex_init(init_path)
    sdscs = _sdsc_files(code_dir)
    frame_sizes = (
        _parse_frame_sizes(args.frame_sizes)
        if args.frame_sizes
        else _infer_frame_sizes_from_headers(original, len(sdscs))
    )
    if len(frame_sizes) != len(sdscs):
        raise ValueError(
            f"frame size count ({len(frame_sizes)}) does not match SDSC count ({len(sdscs)})"
        )
    if sum(frame_sizes) != len(original):
        raise ValueError(
            f"frame sizes sum to {sum(frame_sizes)} but runtime init is {len(original)} bytes"
        )

    restickify_pos = _restickify_position(code_dir)
    starts = [0]
    for size in frame_sizes[:-1]:
        starts.append(starts[-1] + size)
    restickify_start = starts[restickify_pos]
    restickify_size = frame_sizes[restickify_pos]
    restickify_end = restickify_start + restickify_size

    bridge, bridge_source = _bridge_frame(Path(args.bridge_frame_dir).resolve())
    if len(bridge) % 128 != 0:
        raise ValueError(f"bridge frame is not 128-byte aligned: {len(bridge)}")

    bridge_summary = _load_bridge_summary(Path(args.bridge_frame_dir).resolve())
    if args.require_hbm_free:
        hbm_free = ((bridge_summary.get("frame") or {}).get("hbm_free"))
        if hbm_free is not True:
            raise ValueError(f"bridge summary does not prove hbm_free=true: {hbm_free}")

    replacements: dict[int, tuple[bytes, str]] = {
        restickify_pos: (bridge, bridge_source),
    }
    for item in args.replacement_frame or []:
        position, replacement_path = _parse_replacement_frame(item)
        if position >= len(frame_sizes):
            raise ValueError(
                f"replacement frame index {position} is out of range for "
                f"{len(frame_sizes)} frames"
            )
        replacement, source = _replacement_frame(
            replacement_path.resolve(),
            clear_sentinel=position > 0,
        )
        if len(replacement) % 128 != 0:
            raise ValueError(
                f"replacement frame {replacement_path} is not 128-byte aligned: "
                f"{len(replacement)}"
            )
        replacements[position] = (replacement, source)

    chunks = []
    for index, start in enumerate(starts):
        original_size = frame_sizes[index]
        if index in replacements:
            chunks.append(replacements[index][0])
        else:
            chunks.append(original[start : start + original_size])
    patched = b"".join(chunks)
    _write_hex_init(init_path, patched)
    metadata = {
        "segment_size": _update_segment_size(code_dir, len(patched) // 128),
        "loadprogram_to_device_dsg": _update_loadprogram_dsg(code_dir, len(patched)),
        "spyrecode": _update_spyrecode(code_dir, patched),
    }

    summary = {
        "status": "patched",
        "source_code_dir": str(source_dir),
        "code_dir": str(code_dir),
        "runtime_init": str(init_path),
        "sdsc_files": [path.name for path in sdscs],
        "frame_sizes": frame_sizes,
        "frame_starts": starts,
        "original_bytes": len(original),
        "original_flits_128b": len(original) // 128,
        "patched_bytes": len(patched),
        "patched_flits_128b": len(patched) // 128,
        "restickify_position": restickify_pos,
        "restickify_sdsc": sdscs[restickify_pos].name,
        "restickify_start": restickify_start,
        "restickify_start_flit": restickify_start // 128,
        "restickify_original_bytes": restickify_size,
        "bridge_frame_source": bridge_source,
        "bridge_frame_bytes": len(bridge),
        "bridge_frame_flits_128b": len(bridge) // 128,
        "replacement_frames": {
            str(index): {
                "source": source,
                "bytes": len(data),
                "flits_128b": len(data) // 128,
            }
            for index, (data, source) in replacements.items()
        },
        "original_header_word": _header_word(original),
        "restickify_original_header_word": _header_word(original, restickify_start),
        "bridge_header_word": _header_word(bridge),
        "patched_header_word_at_restickify_start": _header_word(patched, restickify_start),
        "metadata": metadata,
        "bridge_summary": {
            "status": bridge_summary.get("status"),
            "contract_source": (
                bridge_summary.get("address_preserving_dataop") or {}
            ).get("contract_source"),
            "tokens": (bridge_summary.get("frame") or {}).get("senprog_token_counts"),
            "hbm_free": (bridge_summary.get("frame") or {}).get("hbm_free"),
        },
    }
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--code-dir", required=True)
    parser.add_argument("--bridge-frame-dir", required=True)
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--summary", default="")
    parser.add_argument(
        "--frame-sizes",
        default="",
        help="Comma-separated frame sizes in bytes. If omitted, infer from init headers.",
    )
    parser.add_argument(
        "--replacement-frame",
        action="append",
        default=[],
        help=(
            "Additional frame replacement formatted as "
            "'<frame-index>:<init.txt-or-code-dir>'. Can be repeated."
        ),
    )
    parser.add_argument("--clean", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--require-hbm-free", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    summary = splice(args)
    if args.summary:
        _write_json(Path(args.summary), summary)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
