#!/usr/bin/env python3
# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Probe-only runtime frame splice for LX-neighbor restickify experiments.

This takes a normal DXP-compiled producer -> ReStickifyOpHBM -> consumer bundle
and replaces the restickify program frame inside ``loadprogram_to_device`` with
an ``InputFetchNeighbor`` frame generated by ``dcg_inpfetch_senprog_probe``.

It is not a production lowering. It is a narrow artifact experiment to answer
whether a descriptor-generated LX-neighbor movement program can be packaged into
the same runtime artifact shape as a normal Torch-Spyre fused bundle.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import struct
import subprocess
from pathlib import Path
from typing import Any


def _read_hex_init(path: Path) -> bytes:
    out = bytearray()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if len(line) != 256:
            raise ValueError(f"{path} has non-256-char init line")
        out.extend(bytes.fromhex(line)[::-1])
    return bytes(out)


def _write_hex_init(path: Path, data: bytes) -> None:
    if len(data) % 128 != 0:
        raise ValueError(f"program frame size must be 128-byte aligned: {len(data)}")
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    for offset in range(0, len(data), 128):
        lines.append(data[offset : offset + 128][::-1].hex())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _clear_sentinel(frame: bytes) -> bytes:
    if len(frame) < 4:
        raise ValueError("program frame is too small to contain a header word")
    word = struct.unpack_from("<I", frame, 0)[0]
    patched = word & 0xFFBFFFFF
    out = bytearray(frame)
    struct.pack_into("<I", out, 0, patched)
    return bytes(out)


def _sdsc_index(path: Path) -> int:
    name = path.name
    if not name.startswith("sdsc_"):
        return 10**9
    try:
        return int(name.split("_", 2)[1])
    except Exception:
        return 10**9


def _restickify_position(code_dir: Path) -> int:
    sdscs = sorted(code_dir.glob("sdsc_*.json"), key=_sdsc_index)
    for idx, path in enumerate(sdscs):
        if "ReStickify" in path.name:
            return idx
        text = path.read_text(encoding="utf-8", errors="replace")
        if "ReStickify" in text:
            return idx
    raise ValueError(f"{code_dir} has no restickify SDSC")


def _runtime_init_path(code_dir: Path) -> Path:
    candidates = sorted((code_dir / "loadprogram_to_device").glob("*/init.txt"))
    preferred = [
        path
        for path in candidates
        if path.parent.name == f"{code_dir.name}-SenProgSend"
    ]
    if len(preferred) == 1:
        return preferred[0]
    if len(candidates) != 1:
        raise ValueError(
            f"expected one loadprogram_to_device/*/init.txt, found {len(candidates)}"
        )
    return candidates[0]


def _debug_frame_sizes(code_dir: Path) -> list[int]:
    sdscs = sorted(code_dir.glob("sdsc_*.json"), key=_sdsc_index)
    sizes = []
    for sdsc in sdscs:
        init = code_dir / "debug" / sdsc.stem / "init.txt"
        if not init.exists():
            raise ValueError(f"missing debug init frame: {init}")
        sizes.append(len(_read_hex_init(init)))
    return sizes


def _run_dxp_debug(code_dir: Path) -> dict[str, Any]:
    debug_root = code_dir / "debug"
    shutil.rmtree(debug_root, ignore_errors=True)
    proc = subprocess.run(
        ["dxp_standalone", "--bundle", "-d", str(code_dir)],
        cwd=code_dir,
        env={**os.environ, "DXP_DEBUG": "1", "DXP_VERBOSE": "0"},
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return {
        "returncode": proc.returncode,
        "stdout_tail": proc.stdout[-4000:],
        "stderr_tail": proc.stderr[-4000:],
    }


def _update_spyrecode(code_dir: Path, data: bytes) -> None:
    spyre_dir = code_dir / "spyreCodeDir"
    if not spyre_dir.exists():
        return
    (spyre_dir / "init_binary.bin").write_bytes(data)
    spyrecode = spyre_dir / "spyrecode.json"
    if not spyrecode.exists():
        return
    payload = json.loads(spyrecode.read_text(encoding="utf-8"))
    for section in ("JobPreparationPlan", "JobExecPlan"):
        for command in payload.get(section, []) or []:
            props = command.get("properties") or {}
            if "size" in props:
                props["size"] = str(len(data))
    spyrecode.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def _update_segment_size(code_dir: Path, flits: int) -> None:
    path = code_dir / "segment_size.json"
    if not path.exists():
        return
    payload = json.loads(path.read_text(encoding="utf-8"))
    segments = payload.get("memReqPerSegment", {})
    const_seg = segments.get("7")
    if isinstance(const_seg, dict):
        const_seg["size"] = flits
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def splice(code_dir: Path, ifn_frame_dir: Path, *, run_dxp_debug: bool) -> dict[str, Any]:
    if run_dxp_debug:
        dxp_debug = _run_dxp_debug(code_dir)
        if dxp_debug["returncode"] != 0:
            raise RuntimeError(
                "DXP debug rerun failed:\n"
                + dxp_debug["stdout_tail"]
                + dxp_debug["stderr_tail"]
            )
    else:
        dxp_debug = {"returncode": None}

    init_path = _runtime_init_path(code_dir)
    original = _read_hex_init(init_path)
    frame_sizes = _debug_frame_sizes(code_dir)
    restickify_pos = _restickify_position(code_dir)
    ifn_frame = (ifn_frame_dir / "init_binary.bin").read_bytes()
    ifn_frame = _clear_sentinel(ifn_frame)

    starts = [0]
    for size in frame_sizes[:-1]:
        starts.append(starts[-1] + size)
    restickify_start = starts[restickify_pos]
    restickify_size = frame_sizes[restickify_pos]
    restickify_end = restickify_start + restickify_size
    if len(original) < restickify_end:
        raise ValueError(
            f"runtime init ({len(original)} bytes) is smaller than debug frames"
        )

    patched = original[:restickify_start] + ifn_frame + original[restickify_end:]
    _write_hex_init(init_path, patched)
    _update_spyrecode(code_dir, patched)
    _update_segment_size(code_dir, len(patched) // 128)

    return {
        "status": "patched",
        "code_dir": str(code_dir),
        "runtime_init": str(init_path),
        "original_bytes": len(original),
        "patched_bytes": len(patched),
        "frame_sizes": frame_sizes,
        "restickify_position": restickify_pos,
        "restickify_start": restickify_start,
        "restickify_original_bytes": restickify_size,
        "ifn_frame_bytes": len(ifn_frame),
        "tail_bytes": len(original) - sum(frame_sizes),
        "dxp_debug": dxp_debug,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--code-dir", required=True)
    parser.add_argument("--ifn-frame-dir", required=True)
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--run-dxp-debug", action="store_true")
    parser.add_argument("--summary", default="")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    code_dir = Path(args.code_dir)
    if args.output_dir:
        output_dir = Path(args.output_dir)
        if output_dir.exists():
            shutil.rmtree(output_dir)
        shutil.copytree(code_dir, output_dir)
        code_dir = output_dir
    summary = splice(
        code_dir,
        Path(args.ifn_frame_dir),
        run_dxp_debug=args.run_dxp_debug,
    )
    if args.summary:
        Path(args.summary).write_text(
            json.dumps(summary, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
